### ISSUE TITLE
Add two buttons to date-time picker

### ISSUE THREAD

**Issue by tdegrunt** [entdec/satis#136]
Add a << and a >> button, to jump years.
Make them a little smaller while we're at it (the area, not the icon):

<img width="423" alt="Screenshot 2024-05-30 at 15 26 53" src="https://github.com/entdec/satis/assets/46554/6b28fadf-6791-48ac-8580-981ad9014036">

**Comment by rparse** [comment]
PR created - https://github.com/entdec/satis/pull/137

**Comment by TwistedClone** [comment]
Already merged, moving to test
