### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by tdegrunt** [entdec/satis#51]
# Functional

We're missing a frontend on satis which shows what components we have and how to use them.
See https://daisyui.com/components/ for how this could be done.

# Technical

Add a frontend to satis, which basically works as a demo.
One introduction page with the page component, with links to all components.
Each component should demo what it's capability is, including documentation.

# Tests

Add browser tests

**Comment by WaQasRPL** [comment]
added system tests for dropdown in oms and removed two bugs in satis dropdown component

https://github.com/boxture/oms/pull/3441
https://github.com/entdec/satis/pull/78
